### ISSUE TITLE
Off-topic - Aurelia

### ISSUE THREAD

**Issue by smolinari** [chrismichaels84/data-manager#39]
Hey Chris.

Hope all is well with you. (And, sorry this doesn't really belong here, as I didn't know how to contact you through other channels.)

I just ran into a thread in the Aurelia Github repo which you started and said, wow, what a coincidence. I've been evaluating Aurelia (at a distance, because I am even less of a front-end dev), but have been seriously thinking of making Aurelia our core front-end framework too. I noticed you mentioned you were also evaluating it. 

How have you found it? Are you completely convinced it is a good framework? Are you also convinced of its modularity being an core and big advantage? 

I personally like how it pushes the front-end framework envelope and I've only read good things about it too. I am very interested in your views of Aurelia.

Scott

**Comment by chrismichaels84** [comment]
I really don't like front-end development. It's just not my cup of tea. So, I've looked at the big ones (angular, ember, jquery, polymer, etc.) and have landed on Aurelia for a couple reasons. First, it uses next-generation standards so its modules and such are going to be more future proof. Ember and Angular are also working in this direction. It's also developed by a solid team with a lot of js experience and its well documented.

But for me, the kicker was its learning curve. I just found it an easier transition for a backend guy like me. I didn't have to worry about the DOM or async stuff as much. It is modular, which I get because of composer and pip. It just fit for my coding style, which meant I could use it without having to get deeper into js. Also, it seemed easier (and has been so far) to use with different CSS frameworks. I like Foundation 5 for the same reasons, and they have played well together for me.

I haven't used it in production, and haven't really even dug into it as I am far away from front end stuff. But I'm convinced its the way to go for me, at least.

**Comment by smolinari** [comment]
Cool. I like Aurelia too. I haven't even worked with it in depth, but I can see the things you noted even from "the outside". This video is also pretty cool. https://channel9.msdn.com/Events/Seth-on-the-Road/DevIntersection-2015/Rob-Eisenberg-on-Aurelia

Scott
